language: d
sudo: false
dist: trusty

os:
    - linux

addons:
    apt:
        packages:
            - libevent-dev
              libssl-dev

d:
    - dmd-2.078.0
    - dmd-2.077.1
    - dmd-2.076.1

script:
    - dub test --compiler=${DC}
